services:
  postgres-test:
    image: postgres:14-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: ideaforge_test
    tmpfs:
      - /var/lib/postgresql/data #  use memory

  redis-test:
    image: redis:alpine
    ports:
      - "6380:6379" # use different port
