name: Unit Tests

on:
  push:
    branches: [master, develop, feature/workspace]
  pull_request:
    branches: [master, develop, feature/workspace]
    paths:
      - "apps/client/**"
      - "apps/api/**"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup .npmrc for Tiptap Pro private registry
        run: |
          echo "link-workspace-packages=true" > .npmrc
          echo "@tiptap-pro:registry=https://registry.tiptap.dev/" >> .npmrc
          echo "//registry.tiptap.dev/:_authToken=${{ secrets.TIPTAP_AUTH_TOKEN }}" >> .npmrc

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate Prisma Client
        run: pnpm --filter @idea/api prisma:generate

      - name: Run API Unit Tests
        run: pnpm --filter @idea/api test

      - name: Run Client Unit Tests
        run: pnpm --filter @idea/client test:run
